### ISSUE TITLE
Error displayed each time someone talks.

### ISSUE THREAD

**Issue by dlmj12** [shdwp/MuteMan#1]
I love this mod, but Im getting an error since the recent updates. Each time a player chats it displays this error.
All functionality is working normally... its just filling my server.log ;)

Minecraft 1.0.0
16:17:48 [INFO] This server is running Craftbukkit version git-Bukkit-1.8.1-R4-17-g04a14f7-b1493jnks (MC: 1.0.0) (Implementing API version 1.0.0-R1-SNAPSHOT)

16:16:33 [SEVERE] Could not pass event PLAYER_CHAT to MuteMan
java.lang.NoClassDefFoundError: com/nijiko/permissions/PermissionHandler
        at sp.bukkit.muteman.Access.canSwear(Access.java:76)
        at sp.bukkit.muteman.MuteListener.onPlayerChat(MuteListener.java:24)
        at org.bukkit.plugin.java.JavaPluginLoader$6.execute(JavaPluginLoader.java:295)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:726)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:714)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:516)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by shdwp** [comment]
Hi there! 
Thanks for "i love this mod" :)
You use PEX? Or another permissions manager? In some features (like adding custom permissions to muted users) muteman is hard-embedded into PEX.

**Comment by dlmj12** [comment]
Hi,

I'm using PermissionsBukkit :)

On Mon, Nov 28, 2011 at 2:32 AM, Vasiliy Horbachenko <
reply@reply.github.com

**Comment by shdwp** [comment]
Only Permissions (and PEX for some features), sorry.
